# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5edc92e4c55c04281dd4d97ac0aedc60920514605ec842425d0f3390bb205077ca3e066f3aae84583cc444a8d5037d2fcf628c34ada207cf4c7e5877b413024

test:
  secret_key_base: 6e1b1b98fe9f66a8021535084f113c91c5975115521a2173b2a73b1f3eeb152b5cebd7986643483e78cc9b0b7ccc95c80f7d8f7eed2366d85ac3b76601ae8c68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
